version: '3.8'

services:
  recipe-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  recipe-management:
    image: msundlana/recipe-management-api:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - recipe-postgres

volumes:
  pgdata:
